//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUDelivery
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DeliveryEntities : DbContext
    {
        public DeliveryEntities()
            : base("name=DeliveryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DetallePedido> DetallePedido { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<rptAgrupadosPedidosClientesMes_Result> rptAgrupadosPedidosClientesMes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptAgrupadosPedidosClientesMes_Result>("rptAgrupadosPedidosClientesMes");
        }
    
        public virtual ObjectResult<rptNumeroPedidos_Result> rptNumeroPedidos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptNumeroPedidos_Result>("rptNumeroPedidos");
        }
    
        public virtual ObjectResult<rptProductosVendidos_Result> rptProductosVendidos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptProductosVendidos_Result>("rptProductosVendidos");
        }
    
        public virtual ObjectResult<rptProductosVendidosMes_Result> rptProductosVendidosMes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptProductosVendidosMes_Result>("rptProductosVendidosMes");
        }
    }
}
